changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: New Features
      labels:
        - feature
    - title: Bug
      labels: 
        - bug
    - title: Other Changes
      labels:
        - "*"
