changelog:
  categories:
    - title: Breaking Changes
      labels:
        - :broken_heart: breaking change
    - title: New Features
      labels:
        - :ice_cube: feature
    - title: Bug
      labels: 
        - :bug: bug
    - title: Other Changes
      labels:
        - "*"
